name: Notify on Push

on:
  push:
    branches:
      - main  # Or any branch you want to monitor

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Send Email Notification
        env:
          SMTP_HOST: smtp.skyelectric.com
          SMTP_PORT: 587
          SMTP_USERNAME: sajid.ali@skyelectric.com
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          TO_EMAIL: "sajid.ali@skyelectric.com"
          FROM_EMAIL: "sajid.ali@skyelectric.com"
        run: |
          SUBJECT="GitHub Notification - Push Event"
          BODY="Hello,\n\nThere has been a push to the repository ${GITHUB_REPOSITORY}.\n\nBest Regards,\nGitHub Actions"

          echo -e "Subject:$SUBJECT\nFrom:$FROM_EMAIL\nTo:$TO_EMAIL\n\n$BODY" | msmtp --host=$SMTP_HOST --port=$SMTP_PORT --auth=login --user=$SMTP_USERNAME --passwordeval="echo $SMTP_PASSWORD" --tls $TO_EMAIL
