name: Notify on Push or Pull Request

on:
  push:
    branches:
      - main  # Or any branch you want to monitor
  pull_request:
    types: [opened, synchronize, closed]  # When a PR is opened, updated, or closed

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get changes made
        id: changes
        run: |
          echo "Changes made:"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changes.txt
          cat changes.txt

      - name: Send Email Notification
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          TO_EMAIL: "sajid.ali@skyelectric.com"
          FROM_EMAIL: "sajid.ali@skyelectric.com"
        run: |
          CHANGES=$(cat changes.txt)
          SUBJECT="GitHub Notification - ${{ github.repository }}"

          # Prepare the email content
          BODY="Hello,\n\nChanges were made in the repository ${{ github.repository }}:\n$CHANGES\n\nBest Regards,\nGitHub Actions"

          # Send the email using msmtp
          echo -e "Subject:$SUBJECT\nFrom:$FROM_EMAIL\nTo:$TO_EMAIL\n\n$BODY" | msmtp --host=$SMTP_HOST --port=$SMTP_PORT --auth=login --user=$SMTP_USERNAME --passwordeval="echo $SMTP_PASSWORD" $TO_EMAIL
